In [2]:
import pandas as pd

df = pd.read_csv("water_insecurity_2023.csv", encoding = 'latin-1')

df.head()

,geoid,name,year,geometry,total_pop,plumbing,percent_lacking_plumbing
0,1003,"Baldwin County, Alabama",2023,"list(list(c(765297.99052762, 765703.765676717,...",253507,271.0,0.106900
1,1069,"Houston County, Alabama",2023,"list(list(c(975267.980555021, 975512.944547447...",108462,30.0,0.027659
2,6037,"Los Angeles County, California",2023,"list(list(c(-2066923.36656991, -2066434.254456...",9663345,5248.0,0.054308
3,6087,"Santa Cruz County, California",2023,"list(list(c(-2284911.84626332, -2282456.220196...",261547,187.0,0.071498
4,6097,"Sonoma County, California",2023,"list(list(c(-2336932.55009848, -2336646.078244...",481812,308.0,0.063925